version: '3'

networks:
  mynetwork:
    driver: bridge

services:

  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 172.*.*.*
      MYSQL_DATABASE: demo
      MYSQL_USER: skeyal
      MYSQL_PASSWORD: skeyal
    volumes:
      - mysql-storage:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  grafana-storage:
  mysql-storage: